<?php

namespace AppBundle\Repository;

/**
 * PozisyonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PozisyonRepository extends \Doctrine\ORM\EntityRepository
{
}
