<?php

namespace AppBundle\Repository;

/**
 * SinavyeriRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SinavyeriRepository extends \Doctrine\ORM\EntityRepository
{
}
