<?php

namespace TanimlamalarBundle\Repository;

/**
 * BirimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BirimRepository extends \Doctrine\ORM\EntityRepository
{
}
