<?php

namespace TanimlamalarBundle\Repository;

/**
 * SikayetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SikayetRepository extends \Doctrine\ORM\EntityRepository
{
}
