<?php

namespace TanimlamalarBundle\Repository;

/**
 * YeterlilikRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YeterlilikRepository extends \Doctrine\ORM\EntityRepository
{
}
