# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.datatable.yeterlilik.liste:
        class: TanimlamalarBundle\Datatables\YeterlilikDatatable
        parent: sg_datatables.datatable.abstract

    app.datatable.birim.liste:
        class: TanimlamalarBundle\Datatables\BirimDatatable
        parent: sg_datatables.datatable.abstract

    app.datatable.sorubankasi.teoriksoru.liste:
        class: SorubankasiBundle\Datatables\TeorikSoruDatatable
        parent: sg_datatables.datatable.abstract