<?php

namespace SorubankasiBundle\Repository;

/**
 * PratikSoruRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PratikSoruRepository extends \Doctrine\ORM\EntityRepository
{
}
