<?php

namespace SorubankasiBundle\Repository;

/**
 * SoruRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoruRepository extends \Doctrine\ORM\EntityRepository
{
}
