<?php

namespace SorubankasiBundle\Repository;

/**
 * TeorikSoruRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeorikSoruRepository extends \Doctrine\ORM\EntityRepository
{
}
