<?php

namespace SorubankasiBundle\Repository;

/**
 * TeorikCevapanahtariRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeorikCevapanahtariRepository extends \Doctrine\ORM\EntityRepository
{
}
