<?php

namespace SorubankasiBundle\Repository;

/**
 * TeorikCevaplarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeorikCevaplarRepository extends \Doctrine\ORM\EntityRepository
{
}
